root = "."
tmp_dir = "tmp"

[build]
bin = "tmp/main.exe"
cmd = "go build -o {{.Output}} {{.Input}}"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]
exclude_file = []
delay = 1000
